force-app/main/default/objects/twogz_credential__c/twogz_credential__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>twogz_credential</label>
</CustomObject>

force-app/main/default/objects/twogz_credential__c/fields/access_token__c.field-meta.xml
<CustomField>
    <fullName>access_token__c</fullName>
    <label>access_token</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/twogz_credential__c/fields/client_Id__c.field-meta.xml
<CustomField>
    <fullName>client_Id__c</fullName>
    <label>client_Id</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/twogz_credential__c/fields/client_secret__c.field-meta.xml
<CustomField>
    <fullName>client_secret__c</fullName>
    <label>client_secret</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/twogz_credential__c/fields/isProduction__c.field-meta.xml
<CustomField>
    <fullName>isProduction__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >Check this field if your are running in production environnment</description>
    <label>isProduction</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/twogz_credential__c/fields/password__c.field-meta.xml
<CustomField>
    <fullName>password__c</fullName>
    <label>password</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/twogz_credential__c/fields/username__c.field-meta.xml
<CustomField>
    <fullName>username__c</fullName>
    <label>username</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AuthService.cls
public with sharing class AuthService {
  public static String getCredential() {
    twogz_credential__c mc = twogz_credential__c.getInstance();
    Map<String, String> request = new Map<String, String>();
    request.put('client_id', mc.client_Id__c);
    request.put('client_secret', mc.client_Secret__c);
    //request.put('username', mc.username__c);
    //request.put('password', mc.password__c + mc.access_token__c);
    request.put('grant_type', 'client_credentials');
    String mapString = String.valueOf(request)
      .replace(',', '&')
      .replace(' ', '')
      .replace('{', '')
      .replace('}', '');

    System.debug(LoggingLevel.DEBUG, 'Request String ' + mapString);

    HttpRequest req = new HttpRequest();
    req.setMethod('POST');
    req.setHeader('Content-Type', 'application/x-www-form-urlencoded');
    req.setEndpoint(
      URL.getOrgDomainUrl().toExternalForm() + '/services/oauth2/token'
    );
    /*   if (mc.isProduction__c) {
      req.setEndpoint('https://login.salesforce.com/services/oauth2/token');
    } else {
      req.setEndpoint('https://test.salesforce.com/services/oauth2/token');
    } */
    req.setBody(mapString);

    Http http = new Http();
    HTTPResponse response = http.send(req);
    String accessToken = '';
    if (response.getStatusCode() == 200) {
      Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(
        response.getBody()
      );
      accessToken = (String) responseMap.get('access_token');
      System.debug(LoggingLevel.DEBUG, 'get Token ok');
    } else {
      accessToken = response.getBody();
      System.debug(LoggingLevel.DEBUG, 'Error: ' + response.toString());
    }
    return accessToken;
  }
}