force-app/main/default/objects/Tgz_log__c/Tgz_log__c.object-meta.xml
<CustomObject>
    <label>Tgz_log</label>
    <nameField>
        <displayFormat>2gz# {00000000}</displayFormat>
        <label>Log_Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tgz_logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tgz_log__c/fields/LayoutObject__c.field-meta.xml
<CustomField>
    <fullName>LayoutObject__c</fullName>
    <label>LayoutObject</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tgz_log__c/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <label>User_Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/tgz_layoutServices/LogHelper.cls
public with sharing class LogHelper {
  @SuppressWarnings
  @AuraEnabled
  public static String insertInLog(
    String layoutFullName,
    String userId,
    String layoutObject
  ) {
    if (layoutFullName == null || userId == null || layoutObject == null) {
      return 'error';
    }
    System.debug(
      LoggingLevel.DEBUG,
      'layoutFullName in loghelper: ' + layoutFullName
    );
    System.debug(LoggingLevel.DEBUG, 'userId in loghelper: ' + userId);
    System.debug(
      LoggingLevel.DEBUG,
      'layoutObject in loghelper: ' + layoutObject
    );
    try {
      Tgz_log__c log = new Tgz_log__c();
      if (
        !Schema.sObjectType.Tgz_log__c.fields.LayoutFullName__c.isUpdateable() ||
        !Schema.sObjectType.Tgz_log__c.fields.User_Id__c.isUpdateable() ||
        !Schema.sObjectType.Tgz_log__c.fields.LayoutObject__c.isUpdateable() ||
        !Schema.sObjectType.Tgz_log__c.fields.LayoutFullName__c.isCreateable() ||
        !Schema.sObjectType.Tgz_log__c.fields.User_Id__c.isCreateable() ||
        !Schema.sObjectType.Tgz_log__c.fields.LayoutObject__c.isCreateable()
      ) {
        System.debug(LoggingLevel.DEBUG, 'Error: fields not updateable');
        return null;
      }
      log.LayoutFullName__c = layoutFullName;
      log.User_Id__c = userId;
      log.LayoutObject__c = layoutObject;
      insert log;
    } catch (DMLException e) {
      System.debug(LoggingLevel.DEBUG, 'Error: ' + e.getMessage());
    }
    return 'success';
  }
}